### ISSUE TITLE
if the replace value add previous data is larger than max MTU will you split it to two MTU ?

### ISSUE THREAD

**Issue by qianguozheng** [rgerganov/nfqsed#1]
Actually, I have many questions want to ask you for help.
1. the replacement size add previous data is larger that max MTU 1500, what will it do ?
2. if I want to process http response, with Content-Type: text.html , and modify the content how could I do to merge several packets into one ? as you know one http packet maybe large, and if it is the content is gzip compressed, I need to decompress,modify, and compress, how should I do ?
or do you have any samples ? 
Thanks a lot.

**Comment by rgerganov** [comment]
1. I am not sure. I guess the packet will be rejected.
2. I don't think that merging packets is going to work (especially for HTTP transfer). One option for HTTP is to maintain state and process packet by packet. It will be very tricky though and I don't have any samples for this.
